const portfolioDesignPreset = {
  theme: {
    extend: {
      fontFamily: {
        sans: ['Pretendard', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#FFF7ED',
          100: '#FFEDD5',
          400: '#EA580C',
          500: '#C2410C',
          600: '#9A3412',
          700: '#7C2D12',
        },
        up: { DEFAULT: '#E03131', bg: '#FFF0F0' },
        live: '#C2410C',
        down: { DEFAULT: '#1971C2', bg: '#EFF8FF' },
        flat: { DEFAULT: '#6B6B6B', bg: '#F5F5F5' },
        ipo: {
          demand: { bg: '#DBEAFE', text: '#1D4ED8' },
          subscribe: { bg: '#FEF3C7', text: '#92400E' },
          listing: { bg: '#ECFDF5', text: '#065F46' },
          review: { bg: '#EDE9FE', text: '#5B21B6' },
        },
        ink: {
          950: '#0F1115',
          900: '#111111',
          800: '#111111',
          700: '#444444',
          600: '#444444',
          500: '#6B7280',
          400: '#6B7280',
          300: '#C7C7C7',
          200: '#EEEEEE',
          100: '#F1EAE1',
          50: '#F8F4EE',
        },
        warn: { bg: '#FFFBEB', border: '#FCD34D', text: '#92400E' },
        overlay: { dark: 'rgba(15,17,21,0.72)', soft: 'rgba(15,17,21,0.08)' },
      },
      borderRadius: {
        xs: '8px',
        sm: '8px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '16px',
        control: '8px',
        card: '12px',
        'card-lg': '16px',
        pill: '9999px',
      },
      boxShadow: {
        card: '0 1px 4px rgba(0,0,0,0.08)',
        'card-hover': '0 8px 24px rgba(15,23,42,0.10)',
        popover: '0 16px 40px rgba(15,23,42,0.14)',
        focus: '0 0 0 3px rgba(154,52,18,0.22)',
      },
      fontSize: {
        display: ['28px', { lineHeight: '36px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'heading-1': ['22px', { lineHeight: '30px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'heading-2': ['18px', { lineHeight: '26px', letterSpacing: '-0.018em', fontWeight: '700' }],
        'heading-3': ['16px', { lineHeight: '24px', letterSpacing: '-0.012em', fontWeight: '700' }],
        'body-1': ['15px', { lineHeight: '24px', letterSpacing: '-0.006em', fontWeight: '400' }],
        'body-2': ['14px', { lineHeight: '22px', letterSpacing: '-0.004em', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        micro: ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'price-xl': ['40px', { lineHeight: '44px', letterSpacing: '-0.05em', fontWeight: '700' }],
        'price-lg': ['24px', { lineHeight: '30px', letterSpacing: '-0.035em', fontWeight: '700' }],
        'price-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'badge-count': ['10px', { lineHeight: '14px', letterSpacing: '0em', fontWeight: '700' }],
      },
      spacing: {
        'ds-0': '0px',
        'ds-0.5': '4px',
        'ds-1': '8px',
        'ds-1.5': '12px',
        'ds-2': '16px',
        'ds-2.5': '20px',
        'ds-3': '24px',
        'ds-4': '32px',
        'ds-6': '48px',
        'ds-8': '64px',
        'page-mobile': 'var(--layout-page-gutter-compact)',
        'page-tablet': 'var(--layout-page-gutter-medium)',
        'page-desktop': 'var(--layout-page-gutter-expanded)',
        'section-mobile': 'var(--layout-section-gap-compact)',
        'section-tablet': 'var(--layout-section-gap-medium)',
        'section-desktop': 'var(--layout-section-gap-expanded)',
        'card-mobile': 'var(--layout-card-gap-compact)',
        'card-tablet': 'var(--layout-card-gap-medium)',
        'card-desktop': 'var(--layout-card-gap-expanded)',
        'pane': 'var(--layout-pane-gap)',
        'card-pad-compact': 'var(--component-card-padding-compact)',
        'card-pad-medium': 'var(--component-card-padding-medium)',
        'card-pad-expanded': 'var(--component-card-padding-expanded)',
        'control-sm': 'var(--size-control-compact)',
        'control-md': 'var(--size-control-default)',
        'control-lg': 'var(--size-control-touch)',
        sidebar: 'var(--layout-sidebar-width)',
        'right-panel': 'var(--layout-supporting-pane-width)',
        topbar: 'var(--layout-topbar-height)',
        'mobile-nav': 'var(--layout-mobile-nav-height)',
        'mobile-nav-safe': 'var(--layout-mobile-nav-safe-height)',
        'mobile-content-safe': 'var(--layout-mobile-content-clearance)',
        'safe-area-bottom': 'env(safe-area-inset-bottom)',
      },
      maxWidth: {
        content: 'var(--layout-content-max)',
        readable: 'var(--layout-reading-max)',
        shell: 'var(--layout-content-max)',
      },
      height: {
        'screen-shell': 'calc(100dvh - 56px)',
        chart: '220px',
        map: '520px',
      },
      maxHeight: {
        'task-list': '560px',
        'task-rail': '400px',
      },
      minHeight: {
        hero: '200px',
        'hero-sang': '180px',
        'hero-sub': '140px',
        stat: '104px',
        'stat-compact': '96px',
        'screen-shell': 'calc(100dvh - 56px)',
        chart: '220px',
        map: '520px',
      },
      minWidth: {
        table: '560px',
        'nav-tap': '72px',
        trend: '80px',
      },
      gridTemplateColumns: {
        'hero-metric': 'minmax(0, 1fr) minmax(280px, 360px)',
        'main-right': 'minmax(0, 1fr) minmax(280px, 320px)',
        'main-340': 'minmax(0, 1fr) minmax(280px, 340px)',
        'main-360': 'minmax(0, 1fr) minmax(300px, 360px)',
        'main-380': 'minmax(0, 1fr) minmax(320px, 380px)',
        'main-420': 'minmax(0, 1fr) minmax(340px, 400px)',
        'content-rail': 'minmax(0, 1fr) minmax(300px, 380px)',
        'rail-content': 'minmax(300px, 380px) minmax(0, 1fr)',
        'dashboard-3': 'minmax(300px, 0.9fr) minmax(400px, 1.2fr) minmax(280px, 0.85fr)',
        'dashboard-primary': 'minmax(0, 1fr) minmax(340px, 0.9fr)',
        'dashboard-secondary': 'minmax(0, 8fr) minmax(280px, 4fr)',
        'search-action': 'minmax(0, 1fr) auto',
        'station-map': 'minmax(320px, 420px) minmax(0, 1fr)',
        'map-search': 'minmax(300px, 2fr) minmax(0, 3fr)',
        'timeline-side': 'minmax(280px, 360px) minmax(0, 1fr)',
        'record-action': '32px minmax(0, 1fr) auto',
        'trend-detail': 'minmax(180px, 220px) minmax(0, 1fr)',
        'station-row': '72px minmax(0, 1fr) 58px',
        'auto-action': 'minmax(0, 1fr) auto',
        'side-320': 'minmax(0, 1fr) minmax(280px, 320px)',
        'filter-pair': 'minmax(0, 1fr) minmax(0, 1fr) 44px',
        'disclosure-filters': 'minmax(0, 1fr) repeat(2, minmax(140px, 180px)) auto',
        'disclosure-summary': 'minmax(0, 1fr) minmax(260px, 290px)',
        'disclosure-three': 'minmax(0, 1.05fr) minmax(0, 0.92fr) minmax(260px, 290px)',
        'balanced-columns': 'minmax(0, 1.05fr) minmax(0, 0.95fr)',
        'balanced-soft': 'minmax(0, 1fr) minmax(0, 0.9fr)',
        'calendar-dashboard': 'minmax(0, 1fr) minmax(280px, 310px) minmax(230px, 260px)',
        'calendar-filters': 'minmax(0, 1fr) repeat(2, minmax(140px, 160px)) auto auto',
        'content-rail-compact': 'minmax(0, 1fr) minmax(220px, 290px)',
        'watch-table': 'minmax(180px, 1.25fr) minmax(84px, 0.62fr) minmax(100px, 0.78fr) minmax(112px, 0.9fr) minmax(86px, 0.54fr) minmax(64px, 0.42fr)',
        'trend-120': 'minmax(0, 1fr) 120px',
        'trend-110': 'minmax(0, 1fr) 110px',
      },
      backgroundImage: {
        'hero-farm': 'var(--hero-farm)',
        'hero-liter': 'var(--hero-liter)',
        'hero-sang': 'var(--hero-sang)',
        'hero-solid': 'linear-gradient(135deg, #111827 0%, #1F2937 100%)',
      },
      screens: {
        compact: '480px',
        tablet: '768px',
        desktop: '1024px',
        wide: '1280px',
        large: '1440px',
      },
      transitionTimingFunction: {
        product: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      borderWidth: {
        3: '3px',
      },
      transitionDuration: {
        fast: '120ms',
        product: '180ms',
      },
    },
  },
  plugins: [],
};

module.exports = {
  ...portfolioDesignPreset,
  content: ['./index.html', './src/**/*.{ts,tsx}'],
};
