export const designSystem = {
  color: {
    ink900: '#111111',
    ink700: '#444444',
    ink500: '#6B7280',
    surface: '#FFFFFF',
    border: '#EEEEEE',
    up: '#E03131',
    down: '#1971C2',
    brand: 'var(--color-primary-600)',
    accentText: 'var(--accent-text)',
    textStrong: 'var(--text-strong)',
    textBody: 'var(--text-body)',
    textMuted: 'var(--text-muted)',
    textCaption: 'var(--text-caption)',
    textPlaceholder: 'var(--text-placeholder)',
    textLink: 'var(--text-link)',
    textBadge: 'var(--text-badge)',
    surfacePage: 'var(--surface-page)',
    surfaceCard: 'var(--surface-card)',
    nonTextBorder: 'var(--border-muted)',
    nonTextDivider: 'var(--divider-muted)',
  },
  type: {
    display: '28px/36px',
    heading1: '22px/30px',
    heading2: '18px/26px',
    heading3: '16px/24px',
    body: '15px/24px',
    caption: '13px/20px',
  },
  spacing: {
    xxs: '4px',
    xs: '8px',
    sm: '12px',
    md: '16px',
    card: '20px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
    display: '64px',
  },
  layout: {
    contentMaxWidth: '1600px',
    readingMaxWidth: '760px',
    pageGutterCompact: '16px',
    pageGutterMedium: '20px',
    pageGutterExpanded: '24px',
    sectionGapCompact: '16px',
    sectionGapMedium: '20px',
    sectionGapExpanded: '20px',
    cardGapCompact: '12px',
    cardGapMedium: '16px',
    cardGapExpanded: '16px',
    paneGap: '16px',
    sidebarWidth: '200px',
    supportingPaneWidth: '304px',
  },
  component: {
    cardPaddingCompact: '16px',
    cardPaddingMedium: '20px',
    cardPaddingExpanded: '20px',
  },
  control: {
    compactHeight: '36px',
    defaultHeight: '40px',
    touchHeight: '44px',
  },
  radius: {
    control: '8px',
    card: '12px',
    cardLarge: '16px',
  },
  breakpoint: {
    compact: '480px',
    tablet: '768px',
    desktop: '1024px',
    wide: '1280px',
    large: '1440px',
  },
  shadow: {
    card: '0 1px 4px rgba(0, 0, 0, 0.08)',
    hover: '0 8px 24px rgba(15, 23, 42, 0.10)',
    focus: 'var(--shadow-focus)',
  },
} as const;

export type DesignSystemToken = typeof designSystem;
